package net.riezebos.bruus.tbd.game.items.effects;

public enum EffectIdentifiers {
    AdrenalineAttackSpeedModifier,
    YellowBossVoidAttackSpeedModifier,
    YellowBossVoidMoveSpeedModifier,
    TazerAttackSpeedModifier,
    TazerDamageModifier,
    CalmInChaosDamageBonusModifier,
    PlasmaCoatedBulletsBurning,
    GasolineDormantExplosion,
    Ignite,
    StickyDynamiteDormantExplosion,
    EnergySyphonHealPlayerOnDeath,
    PlatinumSpongeArmorBonus,
    SelfRepairingSteelHealthRegeneration,
    MoneyPrinterGoldOnDeath,
    SpawnCoinsOnDeath,
    SpawnScrapMetalOnDeath,
    ElectricDestabilizerFreeze,
    DevourerMoveSpeedDebuff,
    DevourerAttackSpeedDebuff,
    MutaliskDeathMissiles,
    ContractOnDeathCounter,
    FlameDetonationDormentExplosion,
    DamageReduction,
    CarrierBeaconArmorBonus,
    CarrierBeaconAttackSpeedBonus,
    EndOfLevelBurn,
    PulsingDroneSlow,
    EmergencyRepairsConstructionIncrease,
    StuivieArmorBonus,
    YellowBossOrbHeal,
    MartyrdomAttackSpeed, ElectroShedding;
}
