name: Build and Package
on:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create custom JRE with jlink
      run: |
        jlink --no-header-files --no-man-pages --compress=2 --strip-debug --module-path $JAVA_HOME/jmods --add-modules java.desktop,java.logging --output myjre

    - name: Package with jpackage
      shell: cmd
      run: |
        jpackage ^
          --input target ^
          --main-jar Game-0.0.1-SNAPSHOT.jar ^
          --main-class main.Main ^
          --runtime-image myjre ^
          --java-options "-Djava.library.path=../app/classes/jinput/jinput-platform/2.0.5/"

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-windows
        path: ./*.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create custom JRE with jlink
      run: |
        jlink --no-header-files --no-man-pages --compress=2 --strip-debug --module-path $JAVA_HOME/jmods --add-modules java.desktop,java.logging --output myjre

    - name: Package with jpackage
      run: |
        jpackage \
          --input target \
          --main-jar Game-0.0.1-SNAPSHOT.jar \
          --main-class main.Main \
          --runtime-image myjre \
          --java-options "-Djava.library.path=../app/classes/jinput/jinput-platform/2.0.5/"

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-macos
        path: ./*.pkg
